### ISSUE TITLE
Fix the unique id

### ISSUE THREAD

**Issue by JunqiZhang0** [ESaaS-4995/WebZero#6]
The current unique id always has an u at the beginning
For example: http://webzero-utest-user.s3-website-us-east-1.amazonaws.com/
the id should be test-user, but here it is utest-user

**Comment by sdh21** [comment]
Fixed. Originally deliberate prefix to avoid null bucket name. Later I thought webzero- is a better prefix.
691b6600c58d8198af852c2cfde17132a9ec475f
